services:
  - type: web
    name: futuremarket-api
    env: docker
    plan: free
    autoDeploy: true
    region: frankfurt
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "8080"
      - key: DATABASE_URL
        fromDatabase:
          name: futuremarket-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: futuremarket-db
    plan: free
    region: frankfurt


